AWSTemplateFormatVersion: "2010-09-09"
Description: Algorand NodeKit (Shell Script) on AWS

Parameters:
  StackName:
    Description: Name of the stack
    Type: String
    Default: algorand-nodekit-aws-cloudformation
  KeyName:
    Description: EC2 KeyPair Name
    Type: AWS::EC2::KeyPair::KeyName
  VpcId:
    Type: AWS::EC2::VPC::Id
  SubnetId:
    Type: AWS::EC2::Subnet::Id

Resources:
  NodeSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Algorand Node Security Group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 4160
          ToPort: 4160
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9100 # Metrics port
          ToPort: 9100
          CidrIp: 0.0.0.0/0 # Restrict to monitoring IP if needed

  AlgorandNode:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: c5.2xlarge # 8 vCPUs, 16 GB RAM
      ImageId: ami-0c614dee691cbbf37 # Amazon Linux 2023 AMI
      KeyName: !Ref KeyName
      Tags:
        - Key: Name
          Value: Algorand-Participation-Node
      BlockDeviceMappings:
        - DeviceName: /dev/xvda # Root volume
          Ebs:
            VolumeSize: 100
            VolumeType: gp3
        - DeviceName: /dev/sdf # Data volume (adjust device name based on AMI)
          Ebs:
            VolumeSize: 500
            VolumeType: gp3
      NetworkInterfaces:
        - DeviceIndex: 0
          AssociatePublicIpAddress: true
          SubnetId: !Ref SubnetId
          GroupSet:
            - !GetAtt NodeSecurityGroup.GroupId
      UserData:
        Fn::Base64: |
          #!/bin/bash
          # Update system and install requirements
          dnf update -y
          dnf install -y wget

Outputs:
  InstanceId:
    Value: !Ref AlgorandNode
  PublicIP:
    Value: !GetAtt AlgorandNode.PublicIp
